/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-10-19 03:36:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.product;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>Shop Kart | Home</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/details.css\"/>\r\n");
      out.write("    <style>\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <nav>\r\n");
      out.write("      <div class=\"navbar\">\r\n");
      out.write("        <div class=\"logo\"><b>Shop Kart</b></div>\r\n");
      out.write("        <div class=\"search-bar\">\r\n");
      out.write("          <form action=\"\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"search product\" />\r\n");
      out.write("            <button>Search</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"sections\">\r\n");
      out.write("          <button>About us</button>\r\n");
      out.write("          <button class=\"cart\">\r\n");
      out.write("            Your cart <img src=\"../../../resources/images/cart.svg\" alt=\"\" />\r\n");
      out.write("          </button>\r\n");
      out.write("          <button class=\"profile\" id=\"profile-btn\">\r\n");
      out.write("            Profile <img src=\"../../../resources/images/profile.svg\" />\r\n");
      out.write("          </button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"profile-form\" id=\"profile-form\">\r\n");
      out.write("      <h2>Hey name ! See your Profile</h2>\r\n");
      out.write("      <div class=\"avatar\">\r\n");
      out.write("        <img src=\"../../../resources/images/avatar.jpg\" alt=\"\" />\r\n");
      out.write("      </div>\r\n");
      out.write("      <div><b>Name :</b> Undefined</div>\r\n");
      out.write("      <div><b>Email-id :</b> Undefined</div>\r\n");
      out.write("      <div><b>Address :</b> Undefined</div>\r\n");
      out.write("      <div><b>Phone number :</b> Undefined</div>\r\n");
      out.write("      <button id=\"update-btn\">Update</button>\r\n");
      out.write("      <button id=\"log-out-btn\">Log out</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"welcome-msg\">Welcome name! to our Ecommerce-website</div>\r\n");
      out.write("    <div class=\"big-banner\">\r\n");
      out.write("      <img src=\"../../../resources/images/banner1.jpg\" alt=\"\" />\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"collection\">\r\n");
      out.write("      <div class=\"msg\">Our Products</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"grid-container\">\r\n");
      out.write("      ");
 for (int i = 0; i < 15; i++) { 
      out.write("\r\n");
      out.write("      <div class=\"grid-element\">\r\n");
      out.write("        <a href=\"#\">\r\n");
      out.write("          <img\r\n");
      out.write("            src=\"../../../resources/images/Shirt_image.jpg\"\r\n");
      out.write("            alt=\"Item 1\"\r\n");
      out.write("          />\r\n");
      out.write("        </a>\r\n");
      out.write("        <p><b> Name : Blue Shirt</b></p>\r\n");
      out.write("        <p>Price : ₹1,200</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"breaker\"></div>\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("      <div class=\"company-name\">\r\n");
      out.write("        <p>E-commerce Website</p>\r\n");
      out.write("        <div>\r\n");
      out.write("          <p class=\"description\">\r\n");
      out.write("            Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam\r\n");
      out.write("            alias optio ipsam harum, ipsum, iste architecto fugit temporibus ut\r\n");
      out.write("            ea suscipit sunt. Saepe?Lorem ipsum dolor sit amet consectetur\r\n");
      out.write("            adipisicing elit. Cumque, dolor soluta ipsum ab eveniet dolorum\r\n");
      out.write("            blanditiis maxime eos quas eum earum magni similique. Reprehenderit\r\n");
      out.write("            sint .\r\n");
      out.write("          </p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"options\">\r\n");
      out.write("        <b>COMPANY</b>\r\n");
      out.write("        <a href=\"\">Home</a>\r\n");
      out.write("        <a href=\"\">About us</a>\r\n");
      out.write("        <a href=\"\">Delivery</a>\r\n");
      out.write("        <a href=\"\">Privacy policy</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"contact-details\">\r\n");
      out.write("        <b>GET IN TOUCH</b>\r\n");
      out.write("        <p><b>Team members</b></p>\r\n");
      out.write("        <a href=\"https://github.com/arco02\">Arco Das</a>\r\n");
      out.write("        <a href=\"https://github.com/BaibhabKarmakar\">Baibhab Karmakar</a>\r\n");
      out.write("        <a href=\"\">Sonu Singh Patar</a>\r\n");
      out.write("        <a href=\"https://github.com/Swarnotaj003\">Swarnotaj Kundu</a>\r\n");
      out.write("        <a href=\"https://github.com/TARIFUDDIN\">Syed Tarifuddin ahmed</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"copyrights\">\r\n");
      out.write("      <div class=\"breaker2\"></div>\r\n");
      out.write("      <div>Copyright 2024 © com.example.dev - All Right Reserved.</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"../../../resources/js/home.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
